assassins-insta-kill-speedrunner: true
compass-tracking: true
compass-give: true
compass-particle: true
compass-particle-in-nether: true
compass-random-different-worlds: true
freeze-assassin-when-seen: true
